# Generated by Django 4.0.6 on 2022-07-27 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('dateCreated', models.DateTimeField(auto_now=True, max_length=255)),
                ('dateApproved', models.DateTimeField(auto_now=True, max_length=255)),
                ('dateModified', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('isSold', models.BooleanField(default=False)),
                ('insurances', models.ManyToManyField(blank=True, to='insurance.insurance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
