# Generated by Django 4.0.5 on 2022-07-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0004_alter_insurance_dateexpires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldFor', models.IntegerField(default=0)),
                ('dateCreated', models.DateTimeField(auto_now=True, max_length=255)),
                ('dateApproved', models.DateTimeField(auto_now=True, max_length=255)),
                ('dateModified', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('insurances', models.ManyToManyField(blank=True, to='insurance.insurance')),
            ],
        ),
    ]
