# Generated by Django 4.0.5 on 2022-07-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insurance_dateexpires'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='insurance',
            field=models.ManyToManyField(blank=True, to='insurance.insurance'),
        ),
    ]
