# Generated by Django 4.0.5 on 2022-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='soldFor',
            new_name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
    ]
