# Generated by Django 4.0.5 on 2022-07-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.IntegerField()),
                ('dateExpires', models.DateTimeField(default=None, max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now=True, max_length=255)),
                ('dateApproved', models.DateTimeField(auto_now=True, max_length=255)),
                ('dateModified', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
        ),
    ]
