# Generated by Django 4.0.6 on 2022-07-27 14:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.IntegerField()),
                ('isPackaged', models.BooleanField(default=False)),
                ('dateExpires', models.DateTimeField(default=datetime.datetime(2023, 7, 27, 0, 0), max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now=True, max_length=255)),
                ('dateApproved', models.DateTimeField(auto_now=True, max_length=255)),
                ('dateModified', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
