# Generated by Django 4.0.5 on 2022-06-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_application_datecreated'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='dateCreated',
        ),
        migrations.AddField(
            model_name='insurance',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application'),
            preserve_default=False,
        ),
    ]
