# Generated by Django 4.0.5 on 2022-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insurance_dateexpires'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='isPackaged',
            field=models.BooleanField(default=False),
        ),
    ]
