# Generated by Django 4.0.5 on 2022-06-24 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_insurance_datecreated_insurance_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='dateApproved',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
