# Generated by Django 4.0.5 on 2022-07-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_insurance_dateexpires'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
