# Generated by Django 4.0.5 on 2022-06-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_insurance_dateapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='premium',
            field=models.FloatField(default=0),
        ),
    ]
