# Generated by Django 4.0.5 on 2022-07-15 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_insurance_ispaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='isPaid',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='dateExpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 0, 0), max_length=255),
        ),
    ]
