# Generated by Django 4.0.5 on 2022-06-28 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_insurance_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='dateExpires',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
