# Generated by Django 4.0.5 on 2022-06-28 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_alter_insurance_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='dateModified',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurance',
            name='dateApproved',
            field=models.DateField(auto_now=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='dateCreated',
            field=models.DateField(auto_now=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='dateExpires',
            field=models.DateField(auto_now=True, max_length=255),
        ),
    ]
