# Generated by Django 4.0.5 on 2022-07-10 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_alter_insurance_dateexpires_alter_insurance_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='dateExpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 0, 0), max_length=255),
        ),
    ]
