# Generated by Django 4.0.5 on 2022-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_premium_application_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='dateCreated',
            field=models.CharField(default=1655725130, max_length=255),
        ),
    ]
