# Generated by Django 4.0.5 on 2022-06-30 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_application_dateapproved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dob',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
