# Generated by Django 4.0.5 on 2022-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_remove_application_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dateApproved',
            field=models.DateTimeField(auto_now=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='dateCreated',
            field=models.DateTimeField(auto_now=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
