# Generated by Django 4.0.5 on 2022-06-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insurance_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='dateCreated',
            field=models.CharField(default=1655676622, max_length=255),
        ),
    ]
