# Generated by Django 4.0.5 on 2022-06-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_insurance_dateexpires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='premium',
            field=models.IntegerField(default=0),
        ),
    ]
