# Generated by Django 4.0.5 on 2022-06-20 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_application_datecreated'),
        ('insurance', '0008_alter_insurance_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurance',
            name='dateCreated',
            field=models.CharField(default=1655742641, max_length=255),
        ),
    ]
