# Generated by Django 4.0.5 on 2022-06-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_insurance_application_alter_insurance_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='dateCreated',
            field=models.CharField(default=1655742878, max_length=255),
        ),
    ]
