# Generated by Django 3.1.5 on 2022-06-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_auto_20220620_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='dateCreated',
            field=models.CharField(default=1655758217, max_length=255),
        ),
    ]
