# Generated by Django 4.0.5 on 2022-06-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_alter_insurance_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='dateCreated',
            field=models.CharField(default=1655807967, max_length=255),
        ),
    ]
