# Generated by Django 4.0.5 on 2022-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_alter_insurance_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='dateApproved',
            field=models.DateField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, max_length=255),
        ),
    ]
