# Generated by Django 3.1.5 on 2022-06-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_application_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dateCreated',
            field=models.CharField(default=1655758077, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
