# Generated by Django 4.0.5 on 2022-06-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20220620_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dateApproved',
            field=models.DateField(auto_now_add=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='dateCreated',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
