# Generated by Django 4.0.5 on 2022-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_application_dateapproved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, max_length=255),
        ),
    ]
