# Generated by Django 4.0.5 on 2022-06-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_application_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dateApproved',
            field=models.DateTimeField(auto_now_add=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, max_length=255),
        ),
    ]
