# Generated by Django 4.0.5 on 2022-06-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_application_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='age',
        ),
    ]
